### ISSUE TITLE
Just saying hi

### ISSUE THREAD

**Issue by mltony** [accessolutions/WebAccessForNVDA#18] opened 2024-01-03 19:24 UTC
Hi WebModules developers,
This is not an issue per se, but I just wanted to stop by and say hi. I am @mltony, author of several NVDA add-ons, including [BrowserNav](https://github.com/mltony/nvda-browser-nav/). I just learned about WebModules recently from @aaclause and I was quite surprised to learn that WebModules is nearly identical in its functionality to QuickJump Bookmarks feature of BrowserNav add-on. What you call markers I called bookmarks in my add-on.
I'm not really sure why I am writing this - I guess just wanted to let you know about existence of BrowserNav bookmarks. If I knew about existence of WebModules I surely won't have spent time implementing bookmarks - that took a lot of effort. I don't think that realistically both projects can converge at some point. But I just wanted to suggest you to increase visibility of your project - for example by publishing it on the official NVDA add-on store. I guess in general it would be better for the community to spread the word and I think the entire NVDA comnmunity would benefit if more add-ons are available and if effort of add-on developers is not reduplicated.
Cheers!
--Tony

**Comment by AAClause** [comment] 2024-01-05 20:22
Thanks @mltony for your comment and your add-ons!

I've been using IndentNav daily for about 3 years now.
As for BrowserNav, I've been evaluating it for the past three days and am truly impressed with its features as well. I much appreciate new QuickNav commands and powerful navigation commands.

In my opinion, BrowserNav is a complement and not a duplicate of WebAccess, despite the similarity between their bookmark features.

> But I just wanted to suggest you to increase visibility of your project - for example by publishing it on the official NVDA add-on store. I guess in general it would be better for the community to spread the word and I think the entire NVDA comnmunity would benefit if more add-ons are available and if effort of add-on developers is not reduplicated.

Totally agree. It's planned! Let's keep your issue open until it appears in the store. :)

**Comment by AAClause** [comment] 2024-01-24 18:49
Here it is, a first version of WebAccess is on the add-on store (dev channel only for now). Issue solved! :) Thanks again @mltony  for your interest.

**Closed as completed by AAClause** 2024-01-24 18:49 UTC
